# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: ru
title: Иван Шихалев
email: shikhalev@gmail.com
author: Иван Шихалев
description: Блог. Склад текстов. И прочее городу и миру...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shikhalev.org" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true
rss: rss

excerpt_separator: <!--more-->

permalink: /:year/:month/:title:output_ext

markdown: kramdown
kramdown:
  parse_block_html: true
  auto_ids: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: shikhalev/jekyll-theme

defaults:
  - scope:
      path: "_posts"
    values:
      layout: nova/post
      image: /assets/img/icon.jpg
      author: Иван Шихалев
  - scope:
      path: "_drafts"
    values:
      layout: nova/post
  - scope:
      path: "_calendars"
    values:
      layout: nova/calendar
      image: /assets/img/icon.jpg
      type: website
      author: Иван Шихалев
  - scope:
      path: "_streams"
    values:
      layout: nova/stream
      image: /assets/img/icon.jpg
      type: website
      author: Иван Шихалев
  - scope:
      path: "_posts/text"
    values:
      hide_last_comments: true

header_pages:
  - _streams/tech.md
  - _streams/photo.md
  - _streams/life.md
  - _streams/text.md
  - _streams/about.md

feed:
  categories:
    - tech
    - pub
    - photo
    - life
    - text
    - best
  excerpt_only: false

collections:
  streams:
    output: true
    permalink: /:path/
  calendars:
    output: true
    permalink: /:path/all

staticman_url: https://shikhalev-comments.herokuapp.com/v3/entry/github/shikhalev/shikhalev.github.io/main/comments
date_format: "%Y.%m.%d"

exclude:
  - .vscode/

# Собственные настройки сайта

comments_json_limit: 20
comments_side_limit: 3
category_page_limit: 10
category_page_maximum: 12
home_page_limit: 12
home_page_maximum: 15
