name: Make Announces

on:
  workflow_dispatch:

jobs:
  announce:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.4
          bundler-cache: true
      - name: Announce
        env:
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          echo "Announce..."
          bundle exec jekyll-is-announcer
      - name: Back push
        uses: jekyll-is/action-jekyll-is-backpush@v1
        with:
          label: 'Jekyll Announce'
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-user-id: ${{ secrets.MY_TG_ID }}
      - name: Copy File
        run: |
          mkdir -p tmp/data
          cp -f _data/announced.json tmp/data/announced.json
      - name: Publish
        uses: jekyll-is/action-jekyll-is-publish@main
        with:
          label: 'Jekyll Announce'
          copy-dir: 'tmp'
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pages-repository: ${{ github.repository }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-user-id: ${{ secrets.MY_TG_ID }}
