name: Jekyll Announce

on:
  schedule:
    - cron: '17 3,7,13,17 * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Bundler Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Middle Cache
        uses: actions/cache@v3
        with:
          path: tmp
          key: ${{ runner.os }}-tmp-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-tmp-
      - name: Announce new posts
        uses: jekyll-is/action-announce@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
