name: Make Announces

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.4
          bundler-cache: true
      - name: Announce
        env:
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          echo "Announce..."
          bundle exec jekyll-is-announcer
      - name: Back push
        env:
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.MY_TG_ID }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "Nothing to do."
          else
            MESSAGE=$(git status --short | sed 's/\\/\\\\/g; s/"/\\"/g; s/[_*[\]()~`>#+\-=|{}.!]/\\&/g')
            git commit -m "generated by announce @ $(date)"
            git push
            if [ -n "$TG_BOT_TOKEN" ] && [ -n "$TG_USER_ID" ]; then
              JSON="{\"chat_id\":\"${TG_USER_ID}\",\"text\":\"Back push from Announce:\n\`\`\`git\n${MESSAGE}\n\`\`\`\n\",\"parse_mode\":\"MarkdownV2\"}"
              curl -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" -H "Content-Type: application/json" -d "${JSON}"
            fi
          fi
      - name: Copy File
        run: |
          mkdir -p tmp/data
          cp -f _data/announced.json tmp/data/announced.json
      - name: Publish
        uses: jekyll-is/action-jekyll-is-publish@v1
        with:
          label: 'Jekyll Announce'
          copy-dir: 'tmp'
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pages-repository: ${{ github.repository }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-user-id: ${{ secrets.MY_TG_ID }}
