name: Build & Deploy Site

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.4
          bundler-cache: true
      - name: Setup ImageMagick
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
      - name: Build
        run: |
          echo "Build..."
          JEKYLL_ENV=production NODE_ENV=production bundle exec jekyll build
          date >> build.txt
      - name: Back push
        env:
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.MY_TG_ID }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "Nothing to do."
          else
            MESSAGE=$(git status --short | sed 's/\\/\\\\/g; s/"/\\"/g; s/[_*[\]()~`>#+\-=|{}.!]/\\&/g')
            git commit -m "generated by build @ $(date)"
            git push
            if [ -n "$TG_BOT_TOKEN" ] && [ -n "$TG_USER_ID" ]; then
              JSON="{\"chat_id\":\"${TG_USER_ID}\",\"text\":\"Back push from Build:\n\`\`\`git\n${MESSAGE}\n\`\`\`\n\",\"parse_mode\":\"MarkdownV2\"}"
              curl -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" -H "Content-Type: application/json" -d "${JSON}"
            fi
          fi
      - name: Publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.MY_TG_ID }}
        run: |
          echo "Publish..."
          if [ -d _site ]; then
            REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            BRANCH=gh-pages
            MESSAGE="published by action @ $(date)"
            cd _site
            git init
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git add .
            git commit -m "$MESSAGE"
            git push --force ${REPO} master:${BRANCH}
            if [ -n "$TG_BOT_TOKEN" ] && [ -n "$TG_USER_ID" ]; then
              JSON="{\"chat_id\":\"${TG_USER_ID}\",\"text\":\"Build: ${MESSAGE}\"}"
              curl -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" -H "Content-Type: application/json" -d "${JSON}"
            fi
          else
            echo "Site not found!"
          fi
