name: Build & Deploy Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.4
          bundler-cache: true
      - name: Setup ImageMagick
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
      - name: Build
        run: |
          echo "Build..."
          JEKYLL_ENV=production NODE_ENV=production bundle exec jekyll build
      - name: Back push
        uses: jekyll-is/action-jekyll-is-backpush@v1
        with:
          label: 'Jekyll Build'
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-user-id: ${{ secrets.MY_TG_ID }}
      - name: Publish
        uses: jekyll-is/action-jekyll-is-publish@v1
        with:
          label: 'Jekyll Build'
          sync-dir: '_site'
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pages-repository: ${{ github.repository }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-user-id: ${{ secrets.MY_TG_ID }}
